version: '3.8'
services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - /opt/mosquitto/config:/mosquitto/config:ro
      - /opt/mosquitto/data:/mosquitto/data
      - /opt/mosquitto/log:/mosquitto/log

  xiaomi_bridge:
    build: ./xiaomi_bridge
    container_name: xiaomi_bridge
    restart: always
    depends_on:
      - mosquitto
